### ISSUE TITLE
Is transport compatible with liblo OSC?

### ISSUE THREAD

**Issue by fferri** [reduzent/netpd-server#1]
I tried to connect a C++ client to netpd. Sending messages from liblo to netpd-server works fine. However I can't receive any of the server's replies.

I already enabled SLIP and TCP_NODELAY. Am I missing something?

```
#include <iostream>
#include <thread>
#include <chrono>

using std::cout;
using std::endl;

#include <lo/lo.h>
#include <lo/lo_cpp.h>

int main(int argc, char *argv[])
{
    lo::ServerThread st(9000, LO_TCP, [](int e, const char* s, const char *t){});
    if(st.is_valid()) {
        st.set_callbacks([&st](){cout << "Thread init: " << static_cast<void*>(&st) << endl;},
                         [](){cout << "Thread cleanup." << endl;});
        cout << "server URL: " << st.url() << endl;

        st.add_method("/server/socket", "i",
                          [&](lo_arg **argv, int argc)
                          {cout << "/server/socket" << argv[0]->i << endl;});
        st.add_method("/chat/listrequest", "i",
                          [&](lo_arg **argv, int argc)
                          {cout << "/chat/listrequest" << argv[0]->i << endl;});
        st.start();

        lo::Address a("localhost", "3025", LO_TCP);
        a.set_stream_slip(1);
        a.set_tcp_nodelay(1);

        // ask for our socket number:
        if(a.send_from(st, "/s/server/socket", "") == -1) {
            cout << "send_from error" << a.errstr() << endl;
        }

        // send a chat message
        if(a.send("/b/chat/msg", "ss", "c++client", "hi") == -1) {
            cout << "send error" << a.errstr() << endl;
        }
    } else {
        cout << "error: cannot create server" << endl;
    }

    while(true)
        std::this_thread::sleep_for(std::chrono::seconds(1));

    return 0;
}
```

**Comment by reduzent** [comment]
I'm sorry, but I'm a total c++ noob. I can't even compile your code with `g++ -o oscclient oscclient.cpp`. I get loads of `undefined reference` errors. I installed liblo-dev. 

If you send me the compiled binary, I might able to investigate a bit further. 

Actually, I haven't tried to connect anything but Pd. It's good to try a few things, like c++ program.

**Comment by fferri** [comment]
You need to pass `-llo` to link to the liblo library, e.g.:

```
c++ netpd-client.cpp -llo -o netpd-client
```

**Comment by fferri** [comment]
I can repeat the test in Python if you prefer it over C++. There should be liblo bindings for Python.

At the moment I'm trying to write an OSC-over-SLIP-over-TCP implementation from scratch in Python using just `socket` module (i.e. raw TCP sockets), but it's going to take some time.

**Comment by fferri** [comment]
Ok, I finished implementing OSC-over-SLIP-over-TCP from scratch in Python, and it works fine:

```
$ python3 netpd-client.py
sending: /s/server/socket []
received: /s/server/num_of_clients [1]
received: /s/server/socket [17]
```

So the issue is definitely in liblo.

I already created radarsat1/liblo#127 as I was suspecting that the liblo server was not using SLIP.

Sorry for the noise :-)

If interested I can share my implementation. But probably there are other functional OSC implementations out there. And hopefully, liblo will get fixed.

**Comment by radarsat1** [comment]
Was this issue closed because something was resolved?

**Comment by reduzent** [comment]
I think @fferri  closed the issue because it was confirmed that netpd-server implemented OSC-over-TCP (actually: OSC-over-SLIP-over-TCP) properly. There is nothing that needs change in the netpd-server. Other OSC implementations should be interoperable with netpd-server.

**Comment by radarsat1** [comment]
Ok thanks, i will make a test case for liblo then. Regards.

**Comment by radarsat1** [comment]
Some fixes in place now, liblo master should now work with this.  Thanks @fferri for bringing it to my attention!
